### Returns all push subscriptions
GET {{BASE_URL}}/push-subs
X-Auth-Token: {{AUTH_TOKEN}}

### Returns push subscription record
GET {{BASE_URL}}/push-subs/12
X-Auth-Token: {{AUTH_TOKEN}}

### Add push subscription 
POST {{BASE_URL}}/push-subs
Content-Type: application/json
X-Auth-Token: {{AUTH_TOKEN}}

{
   "user_agent": "Mozilla/1.0",
   "payload": "{}",
   "tag": "RESTCL"
}

### Delete push subscription
DELETE {{BASE_URL}}/push-subs/12
X-Auth-Token: {{AUTH_TOKEN}}
