
### Returns all subscriptions
GET {{BASE_URL}}/subs
X-Auth-Token: {{AUTH_TOKEN}}

### Returns subscription record by id
GET {{BASE_URL}}/subs/19
X-Auth-Token: {{AUTH_TOKEN}}

### Add new subscription
POST {{BASE_URL}}/subs
Content-Type: application/json
X-Auth-Token: {{AUTH_TOKEN}}

{
   "alias": "Test",
   "event": "presence.update",
   "phone": "101010101010",
   "tag": "RESTCL"
}

### Update subscription
PUT {{BASE_URL}}/subs/25
Content-Type: application/json
X-Auth-Token: {{AUTH_TOKEN}}

{
   "alias": "New alias",
   "enabled": 0,
   "notify": 0
}

### Delete subscription
DELETE {{BASE_URL}}/subs/24
X-Auth-Token: {{AUTH_TOKEN}}
